package com.rsupport.mobile.agent.api.model

class AgentLoginResult {
    var RV_AGENT_ID: String = ""
    var RV_AGENT_SESSIONIP_LENGTH: String = ""
    var RV_AGENT_SESSIONIP: String = ""
    var RV_AGENT_SESSIONPORT: String = ""
    var RV_AGENT_SESSIONIP2: String = ""
    var RV_AGENT_SESSIONPORT2: String = ""
    var RV_AGENT_DISPLAYNAME: String = ""
    var RV_AGENT_SSL: String = ""
    var RV_AGENT_SHAREDFOLDER: String = ""
    var RV_AGENT_SESSIONRESULT_PAGE: String = ""
    var RV_AGENT_ACCOUNTCHANGE_PAGE: String = ""
    var RV_AGENT_CONFIGMODIFY_PAGE: String = ""
    var RV_AGENT_CONFIGQUERY_PAGE: String = ""
    var RV_AGENT_RMTCALLCONNECT_PAGE: String = ""
    var RV_AGENT_RMTCALLDISCONNECT_PAGE: String = ""
    var RV_AGENT_RMTFTPCONNECT_PAGE: String = ""
    var RV_AGENT_RMTFTPDISCONNECT_PAGE: String = ""
    var RV_AGENT_AGENTHELP_PAGE: String = ""
    var RV_AGENT_AUTHWEB_SERVER: String = ""
    var RV_AGENT_AUTHWEB_PORT: String = ""
    var RV_AGENT_AUTHWEB_SERVER2: String = ""
    var RV_AGENT_UPDATECHECK_PAGE: String = ""
    var RV_AGENT_UPDATEADDR: String = ""
    var RV_AGENT_UPDATEPORT: String = ""
    var RV_AGENT_UPDATEADDR2: String = ""
    var RV_AGENT_UPDATEDIR: String = ""
    var RV_AGENT_AUTOSCREENLOCK: String = ""
    var RV_AGENT_AUTOSYSTEMLOCK: String = ""
    var RV_AGENT_ENABLED_EXT: String = ""
    var RV_AGENT_CRASH_SERVER: String = ""
    var RV_AGENT_CRASH_PAGE: String = ""
    var RV_AGENT_RVOEMTYPE: String = ""
    var RV_AGENT_ASSET_TIMER: String = ""
    var RV_AGENT_RANDOMPROCESS: String = ""
    var RV_AGENT_CONNECT_SSL_TYPE: String = ""
    var RV_AGENT_CONNECT_SERVER_TYPE: String = ""
    var RV_AGENT_PUSHSERVER_ADDRESS: String = ""
    var RV_AGENT_PUSHSERVER_PORT: String = ""
    var RV_AGENT_RSPERM_DOWNLOAD_URL: String = ""
    var RV_AGENT_PUSHSERVER_WILLTOPIC: String = ""
    var RV_AGENT_NEWVERSION: String = ""
    var RV_AGENT_PUSH_SSL: Boolean? = false

    var RV_AGENT_LOGIN_URL: String = ""
    var RV_AGENT_LOGOUT_URL: String = ""
    var FCM_REGISTRATION_URL: String = ""
}